import { useQueryUsers } from '@/hooks/users'
import Head from 'next/head'

export default function Home() {
  const { data, isLoading } = useQueryUsers()

  return (
    <>
      <Head>
        <title>Frontend Api Strategy Example-1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <h2>Get Users</h2>
          {isLoading ? (
            <p>Loading...</p>
          ) : (
            <ul className="my-5">
              {data?.map((user) => (
                <li key={user.id}>{user.id} - {user.name} | {user.belonging}</li>
              ))}
            </ul>
          )}
        </section>
        <section>
          <h2>Delete User</h2>
        </section>
      </main>
    </>
  )
}
